# Generated by Django 3.2.4 on 2021-06-23 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfapi', '0004_auto_20210623_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='shelfapi.OrderProduct', to='shelfapi.Product'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo_path',
            field=models.URLField(blank=True),
        ),
    ]
