# Generated by Django 3.2.4 on 2021-06-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfapi', '0006_alter_product_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_path',
            field=models.URLField(blank=True),
        ),
    ]
